USE BaseImagensNASA
GO

CREATE TABLE dbo.CargasImagemNASA(
	Id INT IDENTITY(1,1) NOT NULL,
    DataImagem DATETIME NOT NULL,
    DataCarga DATETIME NOT NULL,
	Titulo VARCHAR(300) NOT NULL,
	Detalhes VARCHAR(MAX) NOT NULL,
	UrlImagem VARCHAR(500) NOT NULL,
	BlobName VARCHAR(200) NOT NULL,
	BlobContainer VARCHAR(200) NOT NULL,
	Copyright VARCHAR(200) NULL,
	MediaType VARCHAR(60) NOT NULL,
	ServiceVersion VARCHAR(60) NOT NULL,
	CONSTRAINT PK_CargaImagensNASA PRIMARY KEY (Id)    
)
GO